# SITE CONFIGURATION
url: "https://www.gedankenshift.de"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: gedankenshift.de | Umdenken. Loslassen. Wohlf端hlen.
  title_short: gedankenshift.de
  favicon: assets/favicon.ico
  description: "Der Blog f端r Perspektivenwechsel | Mehr Gelassenheit und Selbstf端rsorge im Alltag | Selbstbestimmt und gl端cklich leben | Minimalismus und digitale Achtsamkeit" #used by search engines
  image: "assets/img/logo.jpg"

  # Header text
  header_text:
  header_text_feature_image: #"assets/img/xy.jpg"

  # Icons
  rss: true
  email_address: hallo@fraulyoner.de
  instagram: "https://instagram.com/fraulyoner" # TODO: Remove in the future
  pinterest: "https://pinterest.de/fraulyoner"
  homepage: "https://fraulyoner.de/"
  etsy: "https://www.etsy.com/de/shop/fraulyonerDE"

  # Search feature
  search: true

  # Post navigation
  post_navigation: false

  # Related posts
  related_posts: true
  related_posts_max: 3
  related_posts_minCommon: 1

# PAGINATION
paginate: 3
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from]
remote_theme: rohanchandra/type-theme
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
