# SITE CONFIGURATION
baseurl: ""
url: "https://www.gedankenshift.de"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: gedankenshift – Gedankenimpulse für Zufriedenheit & Selbstbestimmung
  title_short: gedankenshift
  favicon: assets/favicon.ico
  description: "Gedankenimpulse für ein selbstbestimmtes Leben | Mehr Zufriedenheit | Weniger Perfektionismus | Mut zu Entscheidungen | Tipps zu Minimalismus und Nachhaltigkeit" #used by search engines
  image: "assets/img/logo.jpg"

  # Header text
  header_text:
  header_text_feature_image: #"assets/img/xy.jpg"

  # Icons
  rss: true
  email_address: hallo@fraulyoner.de
  instagram: "fraulyoner"
  twitter: "fraulyoner"
  homepage: "https://fraulyoner.de/"

  # Search feature
  search: true

  # Post navigation
  post_navigation: false

  # Related posts
  related_posts: true
  related_posts_max: 3
  related_posts_minCommon: 1

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
